---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gf-pv-volume
  namespace: monitoring
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/gf"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gf-pv-claim
  namespace: monitoring
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi